apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp            # CI replaces this (myapp:<short-sha>)
          imagePullPolicy: Never              # use image loaded into Minikube
          ports:
            - containerPort: 8080
          command:
            - sh
            - -lc
            - uvicorn app.main:app --host 0.0.0.0 --port 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: SECRET_TOKEN
      envFrom:
        - configMapRef:
            name: myapp-config
      eng:
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: SECRET_TOKEN
      restartPolicy: Always

