apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      # optional if your GHCR package is private and you created the secret
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: myapp
          image: myapp          # kustomize will replace by digest
          ports:
            - containerPort: 8080
          # ✅ envFrom / env must be inside the container
          envFrom:
            - configMapRef:
                name: myapp-config
          env:
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: SECRET_TOKEN
          # (optional) your probes/resources
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 2
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5

